Expanded configure script
Change-Id: I8df554e594ddaafe5eddad403e50c8ec86428c60

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,25 @@
+echo "Scanning for apt package dependencies"
+
+while IFS="" read -r DEP_PACK || [ -n "$DEP_PACK" ]
+do
+    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $DEP_PACK|grep "install ok installed")
+    # echo Checking for somelib: $PKG_OK
+    if [ "" == "$PKG_OK" ]; then
+    echo "Installing $DEP_PACK"
+    sudo apt --yes install $DEP_PACK
+    else
+        echo "$DEP_PACK is installed"
+    fi
+done < DEPS.txt
+
 echo "Configuring MLog"
 
 if [ ! -d "build" ]; then 
     mkdir build
 fi
 
-cd build && cmake .. || (echo "Cmake config failed $$?"; exit 1)
-make || (echo "Compilation failed $$?"; exit 1)
+cd build && cmake .. || (echo "Cmake config failed: Error $$"; exit 1)
+make || (echo "Compilation failed: Error $$"; exit 1)
 
 echo $@
 
